# Generated by Django 5.2.9 on 2025-12-28 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
