# Generated by Django 5.2.9 on 2025-12-25 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(default='', max_length=100)),
                ('style', models.CharField(max_length=100)),
                ('icons', models.CharField(default='', max_length=100)),
                ('icon_color', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Full-time', 'Full-time'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid'), ('Part-time', 'Part-time')], max_length=100)),
                ('style', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy_name', models.CharField(max_length=100)),
                ('vacancy_description', models.TextField()),
                ('requirements', models.TextField(default='', help_text='Hər tələbi yeni sətirdə yazın')),
                ('company_email', models.EmailField(max_length=254)),
                ('location_work', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('salary_type', models.CharField(choices=[('AZN', 'AZN'), ('ERO', 'ERO'), ('USD', 'USD')], max_length=100)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies_count', to='vacancies.category')),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('type_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.worktype')),
            ],
        ),
    ]
