# Generated by Django 5.2.9 on 2025-12-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Son müraciət tarixi'),
        ),
    ]
